### ISSUE TITLE
Bad English on www.memorysafety.org: 'this risk criteria' (_sic_)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [abetterinternet/website#154]
This [webpage](https://www.memorysafety.org/blog/sudo-and-su/), which seems to be yours (and I found no means of contact other than this github repository) contains the following sentence, which is not English.

> Sudo fits this risk criteria squarely.

The word 'criteria' is plural. What you mean is (I think) the following.

> The program 'sudo' fits all four of those risk criteria.

**Comment by scottmakestech** [comment]
@LinuxOnTheDesktop - I have implemented this suggestion. Thank you!
