### ISSUE TITLE
Path for "Unzip purpose theme to tmp directory"

### ISSUE THREAD

**Issue by tdelmas** [abetterinternet/website#20]
```
# Unzip purpose theme to tmp directory
unzip /home/josh/Downloads/${theme_filename}.zip -d /tmp/
```
I think this was committed by mistake (ping @bdaehlie ):
https://github.com/abetterinternet/website/commit/2e321cedc4ad0309e1356722f3be11109b207ece#diff-ac41b61cff4d88050294742ea13f0588L17

**Comment by jprenken** [comment]
It looks like this was subsequently fixed back in https://github.com/abetterinternet/website/commit/c26415c68bed942b0942e4c0a0eba809c204b7a1.

**Comment by tdelmas** [comment]
Yes!
